//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/1hp_just.html
halflife.wad
decals.wad
liquids.wad
xeno.wad
cstrike.wad
cs_dust.wad
de_piranesi.wad
de_aztec.wad
maps/1hp_just.bsp
maps/1hp_just.txt
