gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
models/w_awp.mdl
models/w_m4a1.mdl
models/w_ak47.mdl
models/w_m3.mdl
models/w_m249.mdl
models/w_sg552.mdl
sound/brgames_music/brg_sound1.wav
sound/brgames_music/brg_sound2.wav
sound/brgames_music/brg_sound3.wav
maps/jail_justice_brgames.res
maps/jail_justice_brgames.bsp
maps/jail_justice_brgames.txt

