//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jb_js_russia.html
halflife.wad
decals.wad
sprites/fire.spr
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
de_airstrip.wad
cs_747.wad
sprites/b-tele1.spr
models/w_awp.mdl
models/winebottle.mdl
sound/ambience/burning1.wav
models/jb_js_russia_mdl/eda_1.mdl
models/jb_js_russia_mdl/tree_les2.mdl
models/jb_js_russia_mdl/tree_les3.mdl
sound/jb_js_russia_snd/sound_1.wav
sound/jb_js_russia_snd/sound_2.wav
sound/jb_js_russia_snd/sound_3.wav
sound/jb_js_russia_snd/sound_4.wav
sound/jb_js_russia_snd/sound_5.wav
sound/jb_js_russia_snd/sound_6.wav
sound/jb_js_russia_snd/sound_7.wav
sound/jb_js_russia_snd/sound_8.wav
jb_js_russia.wad
maps/jb_js_russia.bsp
