//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/35hp_super_mario.html
halflife.wad
sprites/wsplash3.spr
sound/ambience/waterfall3.wav
mario.wad
sprites/palm01.mdl
maps/35hp_super_mario.bsp
