//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/c21_choklad.html
halflife.wad
decals.wad
cstrike.wad
liquids.wad
maps/c21_choklad.bsp
maps/c21_choklad.txt
