
// .res entries (31):
gfx/env/52h03bk.tga
gfx/env/52h03dn.tga
gfx/env/52h03ft.tga
gfx/env/52h03lf.tga
gfx/env/52h03rt.tga
gfx/env/52h03up.tga
models/bush_fern_small.mdl
models/car_ladasp.mdl
models/ground.mdl
models/hos_trash1.mdl
models/hos_trash2.mdl
models/new/flo_grass.mdl
models/new/pipe.mdl
models/new/pipe_stack.mdl
models/new/pred_plant.mdl
models/player/gsg9/gsg9.mdl
sound/cah/midnightcricket.wav
sound/torn_water2.wav
sound/waterrun.wav
sprites/glow01.spr
sprites/spr1n/digits/kznum/x0.spr
sprites/spr1n/digits/kznum/x1.spr
sprites/spr1n/digits/kznum/x2.spr
sprites/spr1n/digits/kznum/x3.spr
sprites/spr1n/digits/kznum/x4.spr
sprites/spr1n/digits/kznum/x5.spr
sprites/spr1n/digits/kznum/x6.spr
sprites/spr1n/digits/kznum/x7.spr
sprites/spr1n/digits/kznum/x8.spr
sprites/spr1n/digits/kznum/x9.spr
sprites/watersmoke.spr
