//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_tuscan.html
overviews/de_tuscan.txt
overviews/de_tuscan.bmp
sprites/yelflare1.spr
models/de_tuscan/tuscan_palmtree1.mdl
models/de_tuscan/tuscan_shade1a.mdl
models/de_tuscan/tuscan_shade3a.mdl
models/de_tuscan/tuscan_grass1a.mdl
models/de_tuscan/tuscan_shade2a.mdl
gfx/env/dustbk.tga
gfx/env/dustdn.tga
gfx/env/dustft.tga
gfx/env/dustlf.tga
gfx/env/dustrt.tga
gfx/env/dustup.tga
maps/de_tuscan.bsp
maps/de_tuscan.txt
