gfx/env/perl_bk.tga
gfx/env/perl_dn.tga
gfx/env/perl_ft.tga
gfx/env/perl_lf.tga
gfx/env/perl_rt.tga
gfx/env/perl_up.tga
models/airfield/a1_heli.mdl
models/airfield/a1_heli_crash.mdl
models/airfield/airport_fuel_truck.mdl
models/airfield/ambulance.mdl
models/airfield/gas_propane.mdl
models/airfield/utility_truck.mdl
maps/gm_airfield.res