//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/hns_multiply.html
halflife.wad
decals.wad
cs_cbble.wad
cstrike.wad
cs_assault.wad
de_aztec.wad
de_vegas.wad
gfx/env/drkgbk.tga
gfx/env/drkgdn.tga
gfx/env/drkgft.tga
gfx/env/drkglf.tga
gfx/env/drkgrt.tga
gfx/env/drkgup.tga
maps/hns_multiply.bsp
