//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jail_midday_v2.html
halflife.wad
decals.wad
liquids.wad
itsitaly.wad
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardup.tga
gfx/env/trainyardbk.tga
gfx/env/trainyardrt.tga
sprites/muzzleflash3.spr
sound/weapons/hks1.wav
models/jail_midday/pi_tree1.mdl
models/jail_midday/pi_tree2.mdl
models/jail_midday/rally_tree4.mdl
models/jail_midday/winebottle.mdl
models/jail_midday/supercow.mdl
models/jail_midday/kir_sau.mdl
models/jail_midday/bench2000.mdl
models/jail_midday/car_bombed.mdl
sound/newjail/bowl.wav
sound/jail_midday/bell.wav
sound/jail_midday/bell2.wav
overviews/jail_midday_v2.txt
maps/jail_midday_v2.bsp
maps/jail_midday_v2.txt
