//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jail_aj_ultimate.html
halflife.wad
decals.wad
liquids.wad
xeno.wad
cs_cbble.wad
cstrike.wad
cs_dust.wad
cs_office.wad
de_aztec.wad
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
maps/jail_aj_ultimate.bsp
