//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jail_arizona.html
halflife.wad
cstrike.wad
cs_dust.wad
sound/ambience/waterrun.wav
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
models/w_mp5.mdl
models/w_ak47.mdl
models/w_m3.mdl
models/w_awp.mdl
models/w_m4a1.mdl
models/w_aug.mdl
models/w_scout.mdl
models/props/bathroom_toilet.mdl
models/w_p90.mdl
maps/jail_arizona.bsp
