maps/kz_antiquity.res
gfx/env/desert02bk.tga
gfx/env/desert02dn.tga
gfx/env/desert02ft.tga
gfx/env/desert02lf.tga
gfx/env/desert02rt.tga
gfx/env/desert02up.tga
models/antiquity/b_tree.mdl
models/antiquity/bush14.mdl
models/antiquity/bush_japan_fern_01.mdl
models/antiquity/byka_bush2.mdl
models/antiquity/deglas3.mdl
models/antiquity/egypt_collone_small.mdl
models/antiquity/fence_01.mdl
models/antiquity/flower.mdl
models/antiquity/p2_vines1.mdl
models/antiquity/palmfam600.mdl
sprites/flames.spr
sprites/watersmoke.spr
sprites/spr1n/digits/kzblt/x0.spr
sprites/spr1n/digits/kzblt/x1.spr
sprites/spr1n/digits/kzblt/x2.spr
sprites/spr1n/digits/kzblt/x3.spr
sprites/spr1n/digits/kzblt/x4.spr
sprites/spr1n/digits/kzblt/x5.spr
sprites/spr1n/digits/kzblt/x6.spr
sprites/spr1n/digits/kzblt/x7.spr
sprites/spr1n/digits/kzblt/x8.spr
sprites/spr1n/digits/kzblt/x9.spr
sound/blueflames.wav
sound/halla_water1.wav
sound/sverga_birds.wav
