//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/kz_aztecblock_b02.html
models/player/gsg9/gsg9.mdl
maps/kz_aztecblock_b02.bsp
