maps/kz_anubis.res
maps/kz_anubis.txt
gfx/env/nature01bk.tga
gfx/env/nature01dn.tga
gfx/env/nature01ft.tga
gfx/env/nature01lf.tga
gfx/env/nature01rt.tga
gfx/env/nature01up.tga
models/anubis/bush14.mdl
models/anubis/bush_japan_fern_01.mdl
models/anubis/flower.mdl
models/anubis/torch.mdl
models/anubis/anubis.mdl
models/anubis/big_anubisGolden.mdl
models/anubis/bush_noleaves.mdl
models/anubis/byka_bush2.mdl
models/anubis/deglas3.mdl
models/anubis/ec_palm2.mdl
models/anubis/palmgroup01.mdl
models/anubis/palmtree_v2.mdl
sprites/anubis/flames.spr
sprites/anubis/watersmoke.spr
sprites/spr1n/digits/kzblt/x0.spr
sprites/spr1n/digits/kzblt/x1.spr
sprites/spr1n/digits/kzblt/x2.spr
sprites/spr1n/digits/kzblt/x3.spr
sprites/spr1n/digits/kzblt/x4.spr
sprites/spr1n/digits/kzblt/x5.spr
sprites/spr1n/digits/kzblt/x6.spr
sprites/spr1n/digits/kzblt/x7.spr
sprites/spr1n/digits/kzblt/x8.spr
sprites/spr1n/digits/kzblt/x9.spr
sound/blueflames.wav
sound/rotating_ww.wav
sound/windyforest.wav
sound/halla_water1.wav