maps/muj_to_qui.bsp
maps/muj_to_qui.res
sound/mujik/electric2.wav
sound/mujik/lmof3.wav
sound/mujik/hqui/banmet.wav
sound/mujik/hqui/chad.wav
sound/mujik/hqui/click.wav
sound/mujik/hqui/flasmj1.wav
sound/mujik/hqui/flasmj2.wav
sound/mujik/hqui/flasmj3.wav
sound/mujik/hqui/flbutm.wav
sound/mujik/hqui/lsou.wav
sound/mujik/hqui/megate.wav
sound/mujik/hqui/pianm.wav
sound/mujik/hqui/regen.wav
sound/mujik/hqui/school1.wav
sound/mujik/hqui/sctum.wav
sound/mujik/hqui/terra.wav
sound/mujik/hqui/vst.wav
sound/mujik/hqui/wincli.wav
sprites/mujik/eyemj.spr
sprites/mujik/flare1.spr
sprites/mujik/krasmj4.spr
sprites/mujik/krasmj2.spr
sprites/mujik/krasmj3.spr
sprites/mujik/nudart.spr
sprites/mujik/eleph/blue3.spr
sprites/mujik/hqui/tim1.spr
sprites/mujik/hqui/tim2.spr
sprites/mujik/hqui/tim3.spr
sprites/mujik/hqui/tim4.spr
sprites/mujik/hqui/tim5.spr